[package]
name = "hyprkey"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
ctrlc = { version = "3.4.7", features = ["termination"] }
notify = "8.1.0"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.2"
